version: 2
jobs:

  build:
    docker:
      - image: circleci/node:8.11-jessie
        environment:
          BRANCH: $CIRCLE_BRANCH
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo npm install -g npm
            npm install
      - run:
          name: Tests
          command: |
            npm test
      - run:
          name: Install cf
          command: |
            mkdir -p $HOME/bin
            export PATH=$HOME/bin:$PATH
            curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.34.0" | tar xzv -C $HOME/bin
      - run:
          name: Login to cloud.gov Staging
          command: |
            export PATH=$HOME/bin:$PATH
            cf login -a https://api.fr.cloud.gov -u ${CF_USER} -p ${CF_PASS} -o ${CF_ORG} -s ${CF_SPACE}
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "develop" ]; then
              cf push  cf-example-${CIRCLE_BRANCH}
            fi

